name: e_commerce
description: "E-Commerce Application is a comprehensive solution that offers a
  seamless shopping experience for users"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.3.10
  flutter_offline: ^2.1.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  injectable: ^2.3.5
  intl: ^0.19.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
